Fix HDF5 read: replace undefined 'p' with 'storage_'
Fixes compilation error in read_h5_did() where undefined variable 'p'
was used instead of the storage policy member 'storage_'.

Error: use of undeclared identifier 'p'
Fixed: H5Dread(..., storage_.data()) instead of p.data()

This was likely a typo/refactoring oversight in the HDF5 reading code.